title: Sarah Guthals, PhD
description: Sarah Guthals is a social software engineer and entrepreneur that focuses her life on providing access to high quality computer science education to kids everywhere. With a Ph.D. in Computer Science from University of California, San Diego, her passion is to design products, software, and companies that focus on engaging kids. Sarah builds curriculum around coding, teaches teachers about coding, writes books for kids around technology, and is one of Forbes 30 Under 30 in Science for her work in Computer Science Education.
twitter_username: thewecanzone
github_username: sarah-wecan
theme: jekyll-theme-cayman
